I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/options.rpy", line 21, in script
    define gui.show_name = false
  File "game/options.rpy", line 21, in <module>
    define gui.show_name = false
NameError: name 'false' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/options.rpy", line 21, in script
    define gui.show_name = false
  File "C:\Users\lowda\Downloads\renpy-8.2.0-sdk.7z\renpy-8.2.0-sdk\renpy\ast.py", line 2219, in execute
    self.set()
  File "C:\Users\lowda\Downloads\renpy-8.2.0-sdk.7z\renpy-8.2.0-sdk\renpy\ast.py", line 2233, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\lowda\Downloads\renpy-8.2.0-sdk.7z\renpy-8.2.0-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/options.rpy", line 21, in <module>
    define gui.show_name = false
NameError: name 'false' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.0.24012702
International Serious Game 1.0
Mon Mar 18 00:21:07 2024
